Parameters:
      SecurityGroups:
        Type: List<String>
      AllocatedStorage: 
        Type: String 
      DBInstanceClass: 
        Type: String
      Engine:
        Type: String
      MasterUsername: 
        Type: String
      MasterUserPassword: 
        Type: String
      DeletionPolicy: 
        Type: String 
Resources:
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSecurityGroups: !Ref SecurityGroups
      AllocatedStorage: !Ref AllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      Engine: !Ref Engine
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword 
      DeletionPolicy: !Ref DeletionPolicy
Outputs:
  RDSId:
    Value: !Ref MyDB 
