Parameters:
      SecurityGroups:
        Type: List<String>
      AllocatedStorage: 
        Type: String 
      DBInstanceClass: 
        Type: String
      Engine:
        Type: String
      MasterUsername: 
        Type: String
      MasterUserPassword: 
        Type: String
      DeletionPolicy: 
        Type: String 
Resources:
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSecurityGroups:
      - Ref: MyDbSecurityByEC2SecurityGroup
      - Ref: MyDbSecurityByCIDRIPGroup
      AllocatedStorage: '5'
      DBInstanceClass: db.m1.small
      Engine: MySQL
      MasterUsername: MyName
      MasterUserPassword: MyPassword
      DeletionPolicy: Snapshot  
  
