Parameters:
  VpcId:
    Type: String
  NameTag:
    Type: String
  DestinationCidrBlock: 
    Type: String
  NatGatewayId: 
    Type: String
Resources:
  RouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties: 
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Ref NameTag  
  Route:
    Type: "AWS::EC2::Route"
    Properties: 
      DestinationCidrBlock: !Ref DestinationCidrBlock
      NatGatewayId: !Ref NatGatewayId
      RouteTableId: !Ref RouteTable
Outputs:
  RouteTable:
    Value: !Ref RouteTable
