Parameters:
  SubnetId:
    Type: String
  RouteTableId:
    Type: String
Resources:
  TableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTableId
      SubnetId: !Ref SubnetId
