Parameters: 
  CidrBlock:
    Type: String 
    Default: "10.0.0.0/16"
  EnableDnsSupport:
    Type: String
    Default: "false"
  EnableDnsHostnames:
    Type: String
    Default: "false"
  InstanceTenacy:
    Type: String
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: !Ref EnableDnsSupport 
      EnableDnsHostnames: !Ref EnableDnsHostnames 
      InstanceTenancy: !Ref InstanceTenacy
      Tags:
      - Key: Name
        Value: vpc
Outputs:
  VPCid:
    Value: !Ref myVPC
    Export:
      Name: !Sub "VPCID"
